services:

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nlwg55wd
      POSTGRES_DB: nfb_db
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nfb_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  bot:
    build:
      context: .
    restart: on-failure
    volumes:
      - ./config.local.hcl:/app/config.local.hcl:ro
    ports:
      - "8881:8881"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:
